echo "window.__ENV__ = {\
API_MODEL: '${API_MODEL}',\
API_BASE: '${API_BASE}',\
API_BUYER: '${API_BUYER}',\
API_SELLER: '${API_SELLER}',\
API_ADMIN: '${API_ADMIN}',\
DOMAIN_BUYER_PC: '${DOMAIN_BUYER_PC}',\
DOMAIN_BUYER_WAP: '${DOMAIN_BUYER_WAP}',\
DOMAIN_SELLER: '${DOMAIN_SELLER}',\
DOMAIN_ADMIN: '${DOMAIN_ADMIN}',\
DOMAIN_DECOR: '${DOMAIN_DECOR}',\
DOMAIN_CONSOLE: '${DOMAIN_CONSOLE}',\
DOMAIN_PLATFORM: '${DOMAIN_PLATFORM}'\
}" > /app/buyer/static/js/envs.js

echo "window.__ENV__ = {\
API_MODEL: '${API_MODEL}',\
API_BASE: '${API_BASE}',\
API_BUYER: '${API_BUYER}',\
API_SELLER: '${API_SELLER}',\
API_ADMIN: '${API_ADMIN}',\
DOMAIN_BUYER_PC: '${DOMAIN_BUYER_PC}',\
DOMAIN_BUYER_WAP: '${DOMAIN_BUYER_WAP}',\
DOMAIN_SELLER: '${DOMAIN_SELLER}',\
DOMAIN_ADMIN: '${DOMAIN_ADMIN}',\
DOMAIN_DECOR: '${DOMAIN_DECOR}',\
DOMAIN_CONSOLE: '${DOMAIN_CONSOLE}',\
DOMAIN_PLATFORM: '${DOMAIN_PLATFORM}'\
}" > /app/seller/static/js/envs.js

echo "window.__ENV__ = {\
API_MODEL: '${API_MODEL}',\
API_BASE: '${API_BASE}',\
API_BUYER: '${API_BUYER}',\
API_SELLER: '${API_SELLER}',\
API_ADMIN: '${API_ADMIN}',\
DOMAIN_BUYER_PC: '${DOMAIN_BUYER_PC}',\
DOMAIN_BUYER_WAP: '${DOMAIN_BUYER_WAP}',\
DOMAIN_SELLER: '${DOMAIN_SELLER}',\
DOMAIN_ADMIN: '${DOMAIN_ADMIN}',\
DOMAIN_DECOR: '${DOMAIN_DECOR}',\
DOMAIN_CONSOLE: '${DOMAIN_CONSOLE}',\
DOMAIN_PLATFORM: '${DOMAIN_PLATFORM}'\
}" > /app/admin/static/js/envs.js

echo "window.__ENV__ = {\
API_MODEL: '${API_MODEL}',\
API_BASE: '${API_BASE}',\
API_BUYER: '${API_BUYER}',\
API_SELLER: '${API_SELLER}',\
API_ADMIN: '${API_ADMIN}',\
DOMAIN_BUYER_PC: '${DOMAIN_BUYER_PC}',\
DOMAIN_BUYER_WAP: '${DOMAIN_BUYER_WAP}',\
DOMAIN_SELLER: '${DOMAIN_SELLER}',\
DOMAIN_ADMIN: '${DOMAIN_ADMIN}',\
DOMAIN_DECOR: '${DOMAIN_DECOR}',\
DOMAIN_CONSOLE: '${DOMAIN_CONSOLE}',\
DOMAIN_PLATFORM: '${DOMAIN_PLATFORM}'\
}" > /app/decor/js/envs.js
